# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
          - script: |
              npm install
              npm run build
            displayName: 'npm install, build and test'
      - job: deploy
        dependsOn: Build
        displayName: Deploy 
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'muhaimin-ssh'
              # runOptions: 'commands' 
              # commands: cd app && git checkout main && git pull && /home/azureuser/.nvm/versions/node/v16.0.0/bin/pm2 startOrRestart ecosystem.json
              runOptions: 'inline'
              inline: |
                cd app
                git checkout main
                git pull
                /home/azureuser/.nvm/versions/node/v16.0.0/bin/npm install
                /home/azureuser/.nvm/versions/node/v16.0.0/bin/npm run build
                /home/azureuser/.nvm/versions/node/v16.0.0/bin/pm2 restart app
              failOnStdErr: false